// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.31.1
// source: proto/catalog/catalog.proto

package catalog_v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Plant struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	Id                   int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description          string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	WateringIntervalDays int32                  `protobuf:"varint,4,opt,name=watering_interval_days,json=wateringIntervalDays,proto3" json:"watering_interval_days,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *Plant) Reset() {
	*x = Plant{}
	mi := &file_proto_catalog_catalog_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Plant) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Plant) ProtoMessage() {}

func (x *Plant) ProtoReflect() protoreflect.Message {
	mi := &file_proto_catalog_catalog_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Plant.ProtoReflect.Descriptor instead.
func (*Plant) Descriptor() ([]byte, []int) {
	return file_proto_catalog_catalog_proto_rawDescGZIP(), []int{0}
}

func (x *Plant) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Plant) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Plant) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Plant) GetWateringIntervalDays() int32 {
	if x != nil {
		return x.WateringIntervalDays
	}
	return 0
}

type GetPlantRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PlantId       int32                  `protobuf:"varint,1,opt,name=plant_id,json=plantId,proto3" json:"plant_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPlantRequest) Reset() {
	*x = GetPlantRequest{}
	mi := &file_proto_catalog_catalog_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPlantRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPlantRequest) ProtoMessage() {}

func (x *GetPlantRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_catalog_catalog_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPlantRequest.ProtoReflect.Descriptor instead.
func (*GetPlantRequest) Descriptor() ([]byte, []int) {
	return file_proto_catalog_catalog_proto_rawDescGZIP(), []int{1}
}

func (x *GetPlantRequest) GetPlantId() int32 {
	if x != nil {
		return x.PlantId
	}
	return 0
}

type GetPlantResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Plant         *Plant                 `protobuf:"bytes,1,opt,name=plant,proto3" json:"plant,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPlantResponse) Reset() {
	*x = GetPlantResponse{}
	mi := &file_proto_catalog_catalog_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPlantResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPlantResponse) ProtoMessage() {}

func (x *GetPlantResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_catalog_catalog_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPlantResponse.ProtoReflect.Descriptor instead.
func (*GetPlantResponse) Descriptor() ([]byte, []int) {
	return file_proto_catalog_catalog_proto_rawDescGZIP(), []int{2}
}

func (x *GetPlantResponse) GetPlant() *Plant {
	if x != nil {
		return x.Plant
	}
	return nil
}

type ListPlantsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListPlantsRequest) Reset() {
	*x = ListPlantsRequest{}
	mi := &file_proto_catalog_catalog_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListPlantsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListPlantsRequest) ProtoMessage() {}

func (x *ListPlantsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_catalog_catalog_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListPlantsRequest.ProtoReflect.Descriptor instead.
func (*ListPlantsRequest) Descriptor() ([]byte, []int) {
	return file_proto_catalog_catalog_proto_rawDescGZIP(), []int{3}
}

type ListPlantsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Plants        []*Plant               `protobuf:"bytes,1,rep,name=plants,proto3" json:"plants,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListPlantsResponse) Reset() {
	*x = ListPlantsResponse{}
	mi := &file_proto_catalog_catalog_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListPlantsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListPlantsResponse) ProtoMessage() {}

func (x *ListPlantsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_catalog_catalog_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListPlantsResponse.ProtoReflect.Descriptor instead.
func (*ListPlantsResponse) Descriptor() ([]byte, []int) {
	return file_proto_catalog_catalog_proto_rawDescGZIP(), []int{4}
}

func (x *ListPlantsResponse) GetPlants() []*Plant {
	if x != nil {
		return x.Plants
	}
	return nil
}

type AddFavoriteRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int32                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	PlantId       int32                  `protobuf:"varint,2,opt,name=plant_id,json=plantId,proto3" json:"plant_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddFavoriteRequest) Reset() {
	*x = AddFavoriteRequest{}
	mi := &file_proto_catalog_catalog_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddFavoriteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddFavoriteRequest) ProtoMessage() {}

func (x *AddFavoriteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_catalog_catalog_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddFavoriteRequest.ProtoReflect.Descriptor instead.
func (*AddFavoriteRequest) Descriptor() ([]byte, []int) {
	return file_proto_catalog_catalog_proto_rawDescGZIP(), []int{5}
}

func (x *AddFavoriteRequest) GetUserId() int32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *AddFavoriteRequest) GetPlantId() int32 {
	if x != nil {
		return x.PlantId
	}
	return 0
}

type AddFavoriteResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddFavoriteResponse) Reset() {
	*x = AddFavoriteResponse{}
	mi := &file_proto_catalog_catalog_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddFavoriteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddFavoriteResponse) ProtoMessage() {}

func (x *AddFavoriteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_catalog_catalog_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddFavoriteResponse.ProtoReflect.Descriptor instead.
func (*AddFavoriteResponse) Descriptor() ([]byte, []int) {
	return file_proto_catalog_catalog_proto_rawDescGZIP(), []int{6}
}

func (x *AddFavoriteResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type GetFavoritesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int32                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetFavoritesRequest) Reset() {
	*x = GetFavoritesRequest{}
	mi := &file_proto_catalog_catalog_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetFavoritesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFavoritesRequest) ProtoMessage() {}

func (x *GetFavoritesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_catalog_catalog_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFavoritesRequest.ProtoReflect.Descriptor instead.
func (*GetFavoritesRequest) Descriptor() ([]byte, []int) {
	return file_proto_catalog_catalog_proto_rawDescGZIP(), []int{7}
}

func (x *GetFavoritesRequest) GetUserId() int32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type GetFavoritesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Favorites     []*Plant               `protobuf:"bytes,1,rep,name=favorites,proto3" json:"favorites,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetFavoritesResponse) Reset() {
	*x = GetFavoritesResponse{}
	mi := &file_proto_catalog_catalog_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetFavoritesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFavoritesResponse) ProtoMessage() {}

func (x *GetFavoritesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_catalog_catalog_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFavoritesResponse.ProtoReflect.Descriptor instead.
func (*GetFavoritesResponse) Descriptor() ([]byte, []int) {
	return file_proto_catalog_catalog_proto_rawDescGZIP(), []int{8}
}

func (x *GetFavoritesResponse) GetFavorites() []*Plant {
	if x != nil {
		return x.Favorites
	}
	return nil
}

var File_proto_catalog_catalog_proto protoreflect.FileDescriptor

const file_proto_catalog_catalog_proto_rawDesc = "" +
	"\n" +
	"\x1bproto/catalog/catalog.proto\x12\n" +
	"catalog.v1\"\x83\x01\n" +
	"\x05Plant\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x124\n" +
	"\x16watering_interval_days\x18\x04 \x01(\x05R\x14wateringIntervalDays\",\n" +
	"\x0fGetPlantRequest\x12\x19\n" +
	"\bplant_id\x18\x01 \x01(\x05R\aplantId\";\n" +
	"\x10GetPlantResponse\x12'\n" +
	"\x05plant\x18\x01 \x01(\v2\x11.catalog.v1.PlantR\x05plant\"\x13\n" +
	"\x11ListPlantsRequest\"?\n" +
	"\x12ListPlantsResponse\x12)\n" +
	"\x06plants\x18\x01 \x03(\v2\x11.catalog.v1.PlantR\x06plants\"H\n" +
	"\x12AddFavoriteRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x05R\x06userId\x12\x19\n" +
	"\bplant_id\x18\x02 \x01(\x05R\aplantId\"/\n" +
	"\x13AddFavoriteResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\".\n" +
	"\x13GetFavoritesRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x05R\x06userId\"G\n" +
	"\x14GetFavoritesResponse\x12/\n" +
	"\tfavorites\x18\x01 \x03(\v2\x11.catalog.v1.PlantR\tfavorites2\xc7\x02\n" +
	"\x0eCatalogService\x12E\n" +
	"\bGetPlant\x12\x1b.catalog.v1.GetPlantRequest\x1a\x1c.catalog.v1.GetPlantResponse\x12K\n" +
	"\n" +
	"ListPlants\x12\x1d.catalog.v1.ListPlantsRequest\x1a\x1e.catalog.v1.ListPlantsResponse\x12N\n" +
	"\vAddFavorite\x12\x1e.catalog.v1.AddFavoriteRequest\x1a\x1f.catalog.v1.AddFavoriteResponse\x12Q\n" +
	"\fGetFavorites\x12\x1f.catalog.v1.GetFavoritesRequest\x1a .catalog.v1.GetFavoritesResponseB:Z8github.com/roman4k-gg/myGarden/pkg/catalog_v1;catalog_v1b\x06proto3"

var (
	file_proto_catalog_catalog_proto_rawDescOnce sync.Once
	file_proto_catalog_catalog_proto_rawDescData []byte
)

func file_proto_catalog_catalog_proto_rawDescGZIP() []byte {
	file_proto_catalog_catalog_proto_rawDescOnce.Do(func() {
		file_proto_catalog_catalog_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_catalog_catalog_proto_rawDesc), len(file_proto_catalog_catalog_proto_rawDesc)))
	})
	return file_proto_catalog_catalog_proto_rawDescData
}

var file_proto_catalog_catalog_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_proto_catalog_catalog_proto_goTypes = []any{
	(*Plant)(nil),                // 0: catalog.v1.Plant
	(*GetPlantRequest)(nil),      // 1: catalog.v1.GetPlantRequest
	(*GetPlantResponse)(nil),     // 2: catalog.v1.GetPlantResponse
	(*ListPlantsRequest)(nil),    // 3: catalog.v1.ListPlantsRequest
	(*ListPlantsResponse)(nil),   // 4: catalog.v1.ListPlantsResponse
	(*AddFavoriteRequest)(nil),   // 5: catalog.v1.AddFavoriteRequest
	(*AddFavoriteResponse)(nil),  // 6: catalog.v1.AddFavoriteResponse
	(*GetFavoritesRequest)(nil),  // 7: catalog.v1.GetFavoritesRequest
	(*GetFavoritesResponse)(nil), // 8: catalog.v1.GetFavoritesResponse
}
var file_proto_catalog_catalog_proto_depIdxs = []int32{
	0, // 0: catalog.v1.GetPlantResponse.plant:type_name -> catalog.v1.Plant
	0, // 1: catalog.v1.ListPlantsResponse.plants:type_name -> catalog.v1.Plant
	0, // 2: catalog.v1.GetFavoritesResponse.favorites:type_name -> catalog.v1.Plant
	1, // 3: catalog.v1.CatalogService.GetPlant:input_type -> catalog.v1.GetPlantRequest
	3, // 4: catalog.v1.CatalogService.ListPlants:input_type -> catalog.v1.ListPlantsRequest
	5, // 5: catalog.v1.CatalogService.AddFavorite:input_type -> catalog.v1.AddFavoriteRequest
	7, // 6: catalog.v1.CatalogService.GetFavorites:input_type -> catalog.v1.GetFavoritesRequest
	2, // 7: catalog.v1.CatalogService.GetPlant:output_type -> catalog.v1.GetPlantResponse
	4, // 8: catalog.v1.CatalogService.ListPlants:output_type -> catalog.v1.ListPlantsResponse
	6, // 9: catalog.v1.CatalogService.AddFavorite:output_type -> catalog.v1.AddFavoriteResponse
	8, // 10: catalog.v1.CatalogService.GetFavorites:output_type -> catalog.v1.GetFavoritesResponse
	7, // [7:11] is the sub-list for method output_type
	3, // [3:7] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_proto_catalog_catalog_proto_init() }
func file_proto_catalog_catalog_proto_init() {
	if File_proto_catalog_catalog_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_catalog_catalog_proto_rawDesc), len(file_proto_catalog_catalog_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_catalog_catalog_proto_goTypes,
		DependencyIndexes: file_proto_catalog_catalog_proto_depIdxs,
		MessageInfos:      file_proto_catalog_catalog_proto_msgTypes,
	}.Build()
	File_proto_catalog_catalog_proto = out.File
	file_proto_catalog_catalog_proto_goTypes = nil
	file_proto_catalog_catalog_proto_depIdxs = nil
}
